baseURL = "https://arlmedia.ca/"
languageCode = "en-us"
title = "ArlMedia"
theme = "arlmediaTheme"
pygmentsUseClasses = true
pygmentsCodefences = true 

[params]
  header = "/images/header/64162562.jpeg"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    pre = "code"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "About"
    pre = "info"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    pre = "mail"
    url = "/contact/"
    weight = 5
  [[menu.main]]
    name = "Resume"
    pre = "file-text"
    url = "https://github.com/AndrewRLloyd88/andrew_lloyd_resume/raw/master/andrew-lloyd-resume.pdf"
    weight = 6



